// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.ArveItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ArveListID")
                        .HasColumnType("int");

                    b.Property<string>("LineItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Total")
                        .HasColumnType("real");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.Property<float>("VatRate")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("ArveListID");

                    b.ToTable("ArveItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ArveList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LineItem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("Arved");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.KlientItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KlientListID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.HasIndex("KlientListID");

                    b.ToTable("KlientItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.KlientList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Kliendid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TellimusItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("GrandTotal")
                        .HasColumnType("real");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<float>("ShippingTotal")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<float>("SubTotal")
                        .HasColumnType("real");

                    b.Property<int>("TellimusListID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TellimusListID");

                    b.ToTable("TellimusItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TellimusList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID");

                    b.ToTable("Tellimused");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToodeItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ToodeListID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ToodeListID");

                    b.ToTable("ToodeItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToodeList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Tooted");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ArveItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.ArveList", "ArveList")
                        .WithMany("Items")
                        .HasForeignKey("ArveListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArveList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.KlientItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.KlientList", "KlientList")
                        .WithMany("Items")
                        .HasForeignKey("KlientListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KlientList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TellimusItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.TellimusList", "TellimusList")
                        .WithMany("Items")
                        .HasForeignKey("TellimusListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TellimusList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToodeItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.ToodeList", "ToodeList")
                        .WithMany("Items")
                        .HasForeignKey("ToodeListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToodeList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ArveList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.KlientList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.TellimusList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToodeList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
